### ISSUE TITLE
ae2 controller visual bug

### ISSUE THREAD

**Issue by copinwr** [GTNewHorizons/DreamAssemblerXXL#171]
bug on newest nightly when leaving the controller without storage cells its transparent and with fluid cells it goes black, normal item cells work
![2024-09-11_11 03 44](https://github.com/user-attachments/assets/2068ab14-d713-419f-a74a-1aad7c7bcb27)
tried messing with the settings and it didnt seem to solve it not even turning translucency off

**Comment by Dream-Master** [comment]
@copinwr are you open a new issue? can you explain what version do you use in the new issue ?

**Comment by copinwr** [comment]
> @copinwr are you open a new issue? can you explain what version do you use in the new issue ?

Sorry about that, i didnt see your reply ill be opening a new issue
