### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by NotWhiteRice** [GTNewHorizons/DreamAssemblerXXL#172]
My laptop had died overnight and I had GTNH running so idk if that did anything, but my game crashes before even showing the window.

[latest.log](https://github.com/user-attachments/files/17045047/latest.log)
[crash-2024-09-18_09.48.41-client.txt](https://github.com/user-attachments/files/17045042/crash-2024-09-18_09.48.41-client.txt)

**Comment by NotWhiteRice** [comment]
I tried reinstalling GTNH, but it didnt fix anything, if that helps.

**Comment by NotWhiteRice** [comment]
Launched normal Minecraft and apparently I need to update my graphics card, still doing that rn so I dont have results yet.

**Comment by NotWhiteRice** [comment]
Somehow my drivers no longer support OpenGL, according to Minecraft

**Comment by NotWhiteRice** [comment]
I fixed my issue, my driver got corrupted somehow and I had to reinstall it entirely.

**Comment by Dream-Master** [comment]
@NotWhiteRice post bugs and issues here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues
