### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/DreamAssemblerXXL#43]
Rather than having just one release per mod, have a list of releases/versions/tags for the mod, and add a dropdown to pick which one is included in which version of the modpack.

1) List of all versions available for a mod
2) A "Modpack Version" structure that picks a specific release of each mod
3) A UI to manage modpack versions and which mods are included

**Comment by boubou19** [comment]
thing is, this won't be availiable for curse mods, unless we add them manually. I Know we can fetch releases for github mods, but for curse mods? ~Provided we keep curse compat~

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/187069390-c46610ff-59c2-44c7-977b-48592e089621.png)
