### ISSUE TITLE
Generate/Update release should only update mods already in the release.  Require explicitly adding new mods to avoid pulling in removed mods.

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/DreamAssemblerXXL#58]
Move side of the mods to the release data instead of having it globally. For example in the 2.1.2.0, there is Botdustries, which is not in later versions as it has been absorbed by GTNH Lanthanides. But because the side is global, you have to disable it when you want to build later versions, and reenable it when you want to build the 2.1.2.0.

Remembering what mods got added/removed between versions isn't really practical.

**Comment by mitchej123** [comment]
Seems to make more sense to have the "generate/update release" only pull from mods already in the release, and require explicitly adding new mods.  The assets are just the pool that it can pull from and it shouldn't automatically pull in new/missing (or in this case deleted) mods.
