### ISSUE TITLE
My mod is not on the Changelog

### ISSUE THREAD

**Issue by Quarri6343** [GTNewHorizons/DreamAssemblerXXL#82]
I saw my mod (Block Renderer) [is present in the dev version](https://github.com/GTNewHorizons/DreamAssemblerXXL/commit/9543d56e2d4387978c959749a873c8092b0fb4c6), but cannot find it in the [changelog](https://github.com/GTNewHorizons/DreamAssemblerXXL/blob/master/releases/changelogs/changelog%20from%202.2.3%20to%202.2.4.md)
(for both 2.2.3 and 2.2.4)

I have asked Colen and he has no idea about it

**Comment by mitchej123** [comment]
You see it in the list of available assets; however it has not (yet) been included in a release manifest: https://github.com/GTNewHorizons/DreamAssemblerXXL/tree/master/releases/manifests
