### ISSUE TITLE
Handle version name change in server.properties

### ISSUE THREAD

**Issue by nwmqpa** [GTNewHorizons/DreamAssemblerXXL#95]
As of now, the version in the `server.properties` file is static and defined in [this project](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/server.properties).

It could be templated in [this line](https://github.com/GTNewHorizons/DreamAssemblerXXL/blob/81c2ce6401c3734fa03a552a3e6358a0df01d12a/src/gtnh/assembler/zip_assembler.py#L71) with the release version, which could be also use for others files needing release name templating

**Comment by boubou19** [comment]
yup, will do when i have some spare time

**Comment by boubou19** [comment]
fixed by https://github.com/GTNewHorizons/DreamAssemblerXXL/pull/142
